sudo: false
language: node_js
node_js:
  - "10"
  - "lts/*"
  - "node"

before_install:
  - echo "No GitHub dependencies allowed" &&
    ! grep '"github:' package-lock.json
  - npm install -g npm@latest

install:
  - npm ci

script:
  # Test the code
  - npm test
  # Test global install of the package
  - npm pack .
  - npm install -g solid-ws-*.tgz

cache: npm

notifications:
  email:
  - solid@janeirodigital.com
  - solid-travis@inrupt.com
